name: pipeline

on:
  push:
  pull_request:
  workflow_dispatch:
      
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    
    - name: Install and test Node
        
      run: |
        cd capstone_project/hello-world/
        npm install
        npm test
        
      
    - name: Build  Docker image
      if: ${{ success() }}
      run: |
        cd capstone_project/hello-world/
        docker build -t container .
